# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20170216_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя'),
        ),
    ]
