# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20170329_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=3, null=True, verbose_name='Оценка'),
        ),
    ]
