# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('type', models.IntegerField(choices=[(0, 'Announce for admins'), (5, 'Announce both for admins and users'), (10, 'Message for users'), (15, 'Full site down')], default=0, verbose_name='Message type')),
                ('closable', models.BooleanField(default=True, verbose_name='Allow to close')),
            ],
            options={
                'verbose_name': 'Maintenance message',
                'verbose_name_plural': 'Maintenance messages',
            },
        ),
    ]
