# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancemessage',
            name='closable',
        ),
    ]
