# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_remove_maintenancemessage_closable'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancemessage',
            name='message_ru',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='maintenancemessage',
            name='message_uk',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
    ]
