# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtext',
            name='search_text_ru',
            field=models.CharField(max_length=512, null=True, verbose_name='Search text'),
        ),
        migrations.AddField(
            model_name='searchtext',
            name='search_text_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Search text'),
        ),
    ]
