# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20170217_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchtext',
            options={'verbose_name': 'Search text', 'verbose_name_plural': 'Search texts'},
        ),
    ]
