# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticblock',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
