# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20170222_1315'),
        ('newsletter', '0003_auto_20170221_1026'),
        ('newsletter', '0003_auto_20170222_0921'),
        ('newsletter', '0003_auto_20170220_1017'),
    ]

    operations = [
    ]
