# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOForPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='The url of the page. For example /contacts', max_length=300, verbose_name='URL')),
                ('meta_title', models.TextField(blank=True, default='', null=True, verbose_name='Meta title')),
                ('meta_h1', models.TextField(blank=True, default='', null=True, verbose_name='Meta H1')),
                ('meta_keywords', models.TextField(blank=True, default='', null=True, verbose_name='Meta keywords')),
                ('meta_description', models.TextField(blank=True, default='', null=True, verbose_name='Meta description')),
                ('meta_seo_text', models.TextField(blank=True, default='', null=True, verbose_name='SEO text')),
            ],
            options={
                'verbose_name': 'SEO For Page',
                'verbose_name_plural': 'SEO For Page',
            },
        ),
    ]
