# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoforpage',
            name='url',
            field=models.CharField(help_text='The url of the page. For example /contacts', max_length=300, unique=True, verbose_name='URL'),
        ),
    ]
