# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='scms_icons', verbose_name='Icon')),
                ('create_date', models.DateField(default=datetime.datetime.today, verbose_name='Create date')),
                ('active_date_start', models.DateField(blank=True, null=True, verbose_name='Active date: start')),
                ('active_date_stop', models.DateField(blank=True, null=True, verbose_name='Active date: stop')),
                ('show_on_full_site', models.BooleanField(default=True, verbose_name='Show on full site version')),
                ('show_on_mobile_site', models.BooleanField(default=True, verbose_name='Show on mobile site version')),
                ('type', models.IntegerField(choices=[(1, 'Foul copy'), (2, 'Published')], default=1, verbose_name='Status')),
                ('template', models.CharField(choices=[('parent', 'Наследовать от родителя'), ('default.html', 'Стандартный шаблон'), ('default_with_reverse_related_data.html', 'Стандартный шаблон с обратно связанными даными')], default='default.html', max_length=200, verbose_name='Template')),
                ('vip', models.BooleanField(verbose_name='VIP')),
                ('preamble', models.TextField(blank=True, null=True, verbose_name='Preamble')),
                ('text', models.TextField(verbose_name='Body text')),
                ('position', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Position')),
                ('meta_title', models.TextField(blank=True, verbose_name='Meta Title')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Meta Keywords')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Category name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static_pages_category_icons', verbose_name='Icon')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('template_category', models.CharField(choices=[('parent', 'Наследовать от родителя'), ('default.html', 'Стандартный шаблон'), ('default_with_reverse_related_data.html', 'Стандартный шаблон с обратно связанными даными')], default='default.html', max_length=200, verbose_name='Rubric template')),
                ('template_news', models.CharField(choices=[('parent', 'Наследовать от родителя'), ('default.html', 'Стандартный шаблон'), ('default_with_reverse_related_data.html', 'Стандартный шаблон с обратно связанными даными')], default='default.html', max_length=200, verbose_name='Article template')),
                ('pagination', models.IntegerField(default=30, verbose_name='Count of articles per page')),
                ('sort', models.IntegerField(choices=[(1, 'Direct'), (2, 'Reverse')], verbose_name='Sort')),
                ('meta_title', models.TextField(blank=True, verbose_name='Meta Title')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Meta Keywords')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('meta_seo_text', models.TextField(blank=True, verbose_name='Meta Text')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='static_pages.PageCategory', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Category info-page',
                'verbose_name_plural': 'Categories info-page',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ManyToManyField(to='static_pages.PageCategory', verbose_name='Category'),
        ),
    ]
