# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='pagecategory',
            options={'verbose_name': 'Page category', 'verbose_name_plural': 'Pages categories'},
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keywords_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_seo_text',
            field=models.TextField(blank=True, verbose_name='Meta Text'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_seo_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Text'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_seo_text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Text'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='preamble_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Preamble'),
        ),
        migrations.AddField(
            model_name='page',
            name='preamble_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Preamble'),
        ),
        migrations.AddField(
            model_name='page',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Body text'),
        ),
        migrations.AddField(
            model_name='page',
            name='text_uk',
            field=models.TextField(null=True, verbose_name='Body text'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='meta_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='meta_keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='meta_keywords_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='meta_seo_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Text'),
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='meta_seo_text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Text'),
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='meta_title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='meta_title_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('parent', 'Наследовать от родителя'), ('default.html', 'Стандартный шаблон')], default='default.html', max_length=200, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='pagecategory',
            name='template_category',
            field=models.CharField(choices=[('parent', 'Наследовать от родителя'), ('default.html', 'Стандартный шаблон')], default='default.html', max_length=200, verbose_name='Rubric template'),
        ),
        migrations.AlterField(
            model_name='pagecategory',
            name='template_news',
            field=models.CharField(choices=[('parent', 'Наследовать от родителя'), ('default.html', 'Стандартный шаблон')], default='default.html', max_length=200, verbose_name='Article template'),
        ),
    ]
