# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_auto_20170209_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='show_on_full_site',
        ),
        migrations.RemoveField(
            model_name='page',
            name='show_on_mobile_site',
        ),
    ]
