# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0003_auto_20170216_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static_pages_icons', verbose_name='Icon'),
        ),
    ]
