# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0006_auto_20170217_1458'),
        ('static_pages', '0004_auto_20170217_1414'),
    ]

    operations = [
    ]
