# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0008_auto_20170321_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_h1_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Meta H1'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_h1_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Meta H1'),
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='meta_h1_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Meta H1'),
        ),
        migrations.AddField(
            model_name='pagecategory',
            name='meta_h1_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Meta H1'),
        ),
    ]
