# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20170131_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Product price'),
        ),
    ]
