# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20170131_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Product quantity'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Price'),
        ),
    ]
