# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20170131_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Shipping data'),
        ),
    ]
