# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20170131_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ('position',), 'verbose_name': 'Order status', 'verbose_name_plural': 'Order statuses'},
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
    ]
