# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20170202_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['position'], 'verbose_name': 'Order status', 'verbose_name_plural': 'Order statuses'},
        ),
        migrations.AddField(
            model_name='order',
            name='language',
            field=models.CharField(max_length=50, null=True, verbose_name='Language'),
        ),
    ]
