# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 13:15
from __future__ import unicode_literals

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20170215_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='extra',
            field=core.fields.UnicodeJSONField(blank=True, null=True, verbose_name='Extra'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra_data',
            field=core.fields.UnicodeJSONField(blank=True, default={}, verbose_name='Extra data'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_data',
            field=core.fields.UnicodeJSONField(blank=True, default={}, verbose_name='Payment data'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_data',
            field=core.fields.UnicodeJSONField(blank=True, default={}, null=True, verbose_name='Shipping data'),
        ),
    ]
