# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20170215_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='language',
            field=models.CharField(max_length=50, null=True, verbose_name='Language'),
        ),
    ]
