# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20170223_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], max_length=100, verbose_name='Discount type'),
        ),
    ]
