# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20170223_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
