# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_auto_20170224_0938'),
        ('checkout', '0009_auto_20170222_1315'),
        ('checkout', '0009_cart_language'),
    ]

    operations = [
    ]
