# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 12:36
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_merge_20170307_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_data',
            field=core.fields.UnicodeJSONField(default={}, verbose_name='User data'),
        ),
    ]
