# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 10:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFromXls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xls_file', models.FileField(upload_to='import_from_xml', verbose_name='Excell file')),
                ('price', models.BooleanField(default=True, verbose_name='Price')),
                ('data_map', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Use this for add shortcuts for export', null=True, verbose_name='Data map')),
                ('short_description', models.BooleanField(default=True, verbose_name='Short description')),
                ('full_description', models.BooleanField(default=True, verbose_name='Description')),
                ('properties', models.BooleanField(default=False, verbose_name='Properties')),
                ('log', models.TextField(blank=True, default='', help_text='Field with errors, after import is done', null=True, verbose_name='Log')),
            ],
            options={
                'verbose_name': 'File for import',
                'verbose_name_plural': 'Files for import',
            },
        ),
    ]
