# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfromxls',
            name='log',
            field=models.TextField(blank=True, default='', help_text='Errors caused in import process', null=True, verbose_name='Log'),
        ),
    ]
