# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 12:40
from __future__ import unicode_literals

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20170216_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfromxls',
            name='data_map',
            field=core.fields.UnicodeJSONField(blank=True, help_text='Use this for add shortcuts for export', null=True, verbose_name='Data map'),
        ),
    ]
