# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogousproducts',
            name='analogous_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analogous', to='catalog.Product', verbose_name='Analogous product'),
        ),
        migrations.AlterField(
            model_name='analogousproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
        ),
    ]
