# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpropertyvalue',
            options={'ordering': ('property__position',)},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='property',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
    ]
