# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170118_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(default=9999, verbose_name='Position'),
        ),
    ]
