# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170127_1141'),
        ('catalog', '0002_auto_20170202_0922'),
    ]

    operations = [
    ]
