# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 14:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnails',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Thumbnails'),
        ),
    ]
