# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_merge_20170214_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Full description'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Full description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_h1_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta H1'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_h1_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Meta H1'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta keywords'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Meta keywords'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='SEO text'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='SEO text'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='productpropertyvalue',
            name='value_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='productpropertyvalue',
            name='value_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='productstatus',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productstatus',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='property',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='property',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
