# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170215_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analogousproducts',
            options={'verbose_name': 'Analogous products', 'verbose_name_plural': 'Analogous products'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['position'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productpropertyvalue',
            options={'ordering': ('property__position',), 'verbose_name': 'Product property value', 'verbose_name_plural': 'Product property values'},
        ),
        migrations.AlterModelOptions(
            name='productstatus',
            options={'verbose_name': 'Product status', 'verbose_name_plural': 'Product statuses'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
    ]
