# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_image_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='catalog/products', verbose_name='Image'),
        ),
    ]
