# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170216_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.PositiveIntegerField(default=9999999, verbose_name='Position'),
        ),
    ]
