# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170216_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpropertyvalue',
            name='slug_value',
            field=models.SlugField(max_length=2096, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='productpropertyvalue',
            name='value',
            field=models.CharField(max_length=2096, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='productpropertyvalue',
            name='value_ru',
            field=models.CharField(max_length=2096, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='productpropertyvalue',
            name='value_uk',
            field=models.CharField(max_length=2096, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(max_length=206, verbose_name='Slug'),
        ),
    ]
