# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170216_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('position',), 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
