# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170216_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seo_text',
            new_name='meta_seo_text',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seo_text_ru',
            new_name='meta_seo_text_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seo_text_uk',
            new_name='meta_seo_text_uk',
        ),
    ]
