# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170216_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyValueIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Icon title')),
                ('position', models.SmallIntegerField(default=999, verbose_name='Position')),
                ('icon', models.ImageField(upload_to='icons', verbose_name='Icon')),
                ('expression', models.TextField(verbose_name='Expression for parsing')),
                ('products', models.ManyToManyField(blank=True, to='catalog.Product', verbose_name='Products')),
                ('properties', models.ManyToManyField(to='catalog.Property', verbose_name='Properties')),
            ],
            options={
                'verbose_name': 'Property value icon',
                'verbose_name_plural': 'Property value icons',
            },
        ),
    ]
