# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170303_1141'),
        ('catalog', '0008_auto_20170217_1458'),
        ('catalog', '0009_auto_20170221_1230'),
        ('catalog', '0007_auto_20170227_1529'),
    ]

    operations = [
    ]
