# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_merge_20170307_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpropertyvalue',
            options={'ordering': ('-property__position',), 'verbose_name': 'Product property value', 'verbose_name_plural': 'Product property values'},
        ),
    ]
