# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_property_print_to_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsorting',
            options={'verbose_name': 'Product sorting', 'verbose_name_plural': 'Product sortings'},
        ),
    ]
