# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20170418_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpropertyvalue',
            options={'ordering': ('property__position',), 'verbose_name': 'Product property value', 'verbose_name_plural': 'Product property values'},
        ),
    ]
