# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20170526_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogousproducts',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
