# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170126_1401'),
        ('users', '0002_auto_20170124_1003'),
    ]

    operations = [
    ]
