# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 10:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20170214_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Extra data'),
        ),
    ]
