# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Template name')),
                ('comment', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Info')),
                ('html_template', models.TextField(default='', verbose_name='HTML')),
            ],
            options={
                'verbose_name': 'Mail template',
                'verbose_name_plural': 'Mail templates',
            },
        ),
    ]
