# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer', models.TextField(blank=True, verbose_name='HTTP referer')),
                ('url', models.TextField(verbose_name='404 url')),
                ('count', models.IntegerField(default=0, verbose_name='Count of 404')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('status_code', models.IntegerField(verbose_name='Status code')),
            ],
            options={
                'verbose_name': 'Response log',
                'verbose_name_plural': 'Response logs',
            },
        ),
    ]
