# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responselog',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='responselog',
            name='url',
            field=models.TextField(verbose_name='Url'),
        ),
    ]
