# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 12:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0007_auto_20170206_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_ua', models.CharField(blank=True, max_length=200, verbose_name='Name UA')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('identificator', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=200, verbose_name='Identificator')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='Phones')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Extra')),
                ('position', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Position')),
                ('identificator', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=200, verbose_name='Identificator')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.City', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Delivery office',
                'verbose_name_plural': 'Delivery offices',
            },
        ),
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('order', models.IntegerField(default=10, verbose_name='Position')),
                ('auto_update', models.BooleanField(default=False, verbose_name='Auto update')),
                ('update_source', models.CharField(blank=True, choices=[('novaposhta', 'NovaPoshta'), ('delivery', 'Delivery')], default='', max_length=30, verbose_name='Update source')),
            ],
            options={
                'verbose_name': 'Delivery service',
                'verbose_name_plural': 'Delivery services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryServiceRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.DeliveryService', verbose_name='Delivery service')),
                ('shipping_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_service', to='checkout.ShippingMethod', verbose_name='Shipping method')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='delivery_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='delivery.DeliveryService', verbose_name='Delivery service'),
        ),
    ]
