# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20170210_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryservice',
            name='auto_update',
        ),
        migrations.AlterField(
            model_name='deliveryoffice',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='delivery.City', verbose_name='City'),
        ),
    ]
