# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20170213_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryservicerelation',
            options={'verbose_name': 'Delivery service relation', 'verbose_name_plural': 'Delivery services relations'},
        ),
    ]
