# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_navigator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricenavigator',
            name='product_from_child_categories',
        ),
        migrations.RemoveField(
            model_name='pricenavigator',
            name='variables',
        ),
    ]
