# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_navigator', '0002_auto_20170222_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricenavigator',
            name='update_rate',
        ),
        migrations.AlterField(
            model_name='pricenavigator',
            name='update_times',
            field=models.CharField(help_text='08:00, 20:00', max_length=300, null=True, verbose_name='Update rate'),
        ),
    ]
