# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_navigator', '0003_auto_20170223_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricenavigator',
            name='update_times',
            field=models.CharField(default='08:00, 20:00', help_text='08:00, 20:00', max_length=300, verbose_name='Update rate'),
            preserve_default=False,
        ),
    ]
