# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('slider', 'Slider'), ('checkbox', 'Checkbox'), ('select', 'Select'), ('radio', 'Radio')], max_length=50, verbose_name='Type')),
                ('realization_type', models.CharField(choices=[('price', 'Price'), ('property', 'Property'), ('status', 'Status')], max_length=50, verbose_name='Realization type')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('help_text', models.CharField(max_length=255, verbose_name='Help text')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('popular', models.BooleanField(default=False, verbose_name='Popular')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('properties', models.ManyToManyField(related_name='filters', to='catalog.Property', verbose_name='Properties')),
            ],
            options={
                'verbose_name': 'Filter',
                'verbose_name_plural': 'Filters',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('regex', models.CharField(max_length=500, verbose_name='Regex')),
                ('value', models.SlugField(verbose_name='Value')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_options', to='filters.Filter', verbose_name='Filter')),
                ('products', models.ManyToManyField(related_name='filter_options', to='catalog.Product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Filter option',
                'verbose_name_plural': 'Filter options',
                'ordering': ('position',),
            },
        ),
    ]
