# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='max_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max price'),
        ),
        migrations.AddField(
            model_name='filter',
            name='min_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Min price'),
        ),
        migrations.AddField(
            model_name='filter',
            name='split_property_values_by',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Split property values by'),
        ),
        migrations.AddField(
            model_name='filter',
            name='use_option_popularity',
            field=models.BooleanField(default=False, verbose_name='Use options popularity'),
        ),
    ]
