# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0003_auto_20170127_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteroption',
            name='products_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Products count'),
        ),
    ]
