# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 14:16
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0007_filteroption_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Max price'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Min price'),
        ),
    ]
