# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0009_auto_20170215_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='help_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Help text'),
        ),
        migrations.AddField(
            model_name='filter',
            name='help_text_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Help text'),
        ),
        migrations.AddField(
            model_name='filter',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='filter',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='filteroption',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='filteroption',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='filteroption',
            name='value_ru',
            field=models.SlugField(null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='filteroption',
            name='value_uk',
            field=models.SlugField(null=True, verbose_name='Value'),
        ),
    ]
