# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0010_auto_20170215_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filteroption',
            name='value_ru',
        ),
        migrations.RemoveField(
            model_name='filteroption',
            name='value_uk',
        ),
    ]
