# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0011_auto_20170216_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
