# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0013_auto_20170315_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteroption',
            name='value',
            field=models.SlugField(max_length=255, verbose_name='Value'),
        ),
    ]
