# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0014_auto_20170315_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='split_property_values_by',
        ),
        migrations.AlterField(
            model_name='filteroption',
            name='regex',
            field=models.TextField(max_length=500, verbose_name='Regex'),
        ),
    ]
