# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0015_auto_20170418_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='apply_by_clicking',
            field=models.BooleanField(default=True, verbose_name='Apply by clicking'),
        ),
    ]
